POST http://localhost:3000/api/users
content-type: application/json

{
    "email": "john@doe.com",
    "password": "test123",
    "name": "Facebook"
}


###
GET http://localhost:3000/api/offers/paginate?location=Warsaw


###
GET http://localhost:3000/api/products

###
POST http://localhost:3000/api/checkout
content-type: application/json

{
    "id": "receP3XsTc6mnUgE6",
    "offerId": 1,
    "quantity": 1
}

###
POST http://localhost:3000/api/users/resetPassword
content-type: application/json

{
    "email": "twitter@gmail.com"
}

###
POST http://localhost:3000/api/users/resetPassword
content-type: application/json

{
    "email": "twitter@gmail.com"
}

###
PUT http://localhost:3000/api/users/resetPassword
content-type: application/json

{
    "resetToken": "cdfa11e1c55b2d019287be9d9d5248d6c4354ce8ed16",
    "password": "test456"
}